import type { Metadata } from "next";
import { Inter, Lora } from "next/font/google";
import "./globals.css";
import ClientProvider from "@/app/providers";
import { makeQueryClient } from "@/lib/queryClient";
import { Toaster } from "@/components/ui/sonner"
import { dehydrate, HydrationBoundary } from "@tanstack/react-query";
import { cookies } from "next/headers";
import { toCamel } from "@/lib/case";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["700", "600", "500", "400"]
})

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  style: "italic",
  weight: ["700", "600", "500", "400"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode
}>) {
  /**
   * because it must run on the server
   */
  const queryClient = makeQueryClient()
  const cookieStore = await cookies()

  await queryClient.prefetchQuery({
    queryKey: ['users'],
    queryFn: async () => {
      const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/users/profile`, {
        cache: 'no-store',
        headers: {
          Cookie: cookieStore.toString()
        }
      })
      
      if (!res.ok) return null
      const data = await res.json()
      console.log("dari server", toCamel(data.data))
      return toCamel(data.data)
    }
  })

  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${lora.variable} antialiased`}
      >
        <ClientProvider>
          <HydrationBoundary state={dehydrate(queryClient)}>
            <Toaster position="top-center"/>
            {children}
            {modal}
          </HydrationBoundary>
        </ClientProvider>
      </body>
    </html>
  );
}
